version: '3.7'

services:

  mongo:
    container_name: adm_boo_mongo
    image: mongo:4.4.20
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    security_opt:
      - seccomp:unconfined
    ports:
      - '27017:27017'
    volumes:
      - ../../../.docker/data/db:/data/db:rw
    networks:
      - adm_boo_services

  app:
    container_name: adm_boo_app
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 8080:8080
    networks:
      - adm_boo_services
    depends_on:
      - mongo

networks:
  adm_boo_services:
    external: true
